### ISSUE TITLE
[REQUEST] make unsubbing user friendly

### ISSUE THREAD

**Issue by mattroot** [JuniorJPDJ/telegram-rss#4]
A retarded idea: wouldn't be removing subscriptions easier if we did this using the feed alias, instead of URL?

Yes, it took me a while to think about this.

Sur fix plz or volte in your house

**Comment by JuniorJPDJ** [comment]
You mean feed title?
I was thinking about this, but I'm lazy fuck and data is stored in not-this-feature-friendly data structure, probably won't fix.

**Comment by JuniorJPDJ** [comment]
Also it would be needed to make this title unique, which is not the case now and not desired behavior in the future.
